// make_words.js
// Reads wordle-answers-alphabetical.txt (one word per line) and writes
// words.js, which contains the words as a JavaScript array.
//
// Run from the project folder with:  node make_words.js

const fs = require("fs");
const path = require("path");

const inputFile = path.join(__dirname, "wordle-answers-alphabetical.txt");
const outputFile = path.join(__dirname, "words.js");

// Read the text file and split it into one entry per line
const text = fs.readFileSync(inputFile, "utf8");

const words = text
  .split(/\r?\n/)                          // handle Windows and Mac/Linux line endings
  .map((line) => line.trim().toLowerCase()) // remove stray spaces, normalise case
  .filter((line) => line.length === 5);     // drop blank lines and anything that isn't 5 letters

// Write the array to its own .js file
const contents =
  "// Auto-generated by make_words.js - do not edit by hand.\n" +
  "const WORDS = " + JSON.stringify(words, null, 2) + ";\n";

fs.writeFileSync(outputFile, contents);

console.log("Wrote " + words.length + " words to " + outputFile);